# Generated by Django 5.2.8 on 2026-04-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={},
        ),
    ]
