# Generated by Django 5.2.8 on 2026-04-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_alter_election_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_list', to='voter.election')),
            ],
            options={
                'unique_together': {('election', 'registration_number')},
            },
        ),
    ]
