# Generated by Django 5.2.8 on 2026-04-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_voter'),
        ('voter', '0003_authorizedvoter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='position',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='section',
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnonymousBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.position')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.voter')),
            ],
            options={
                'unique_together': {('voter', 'position')},
            },
        ),
        migrations.DeleteModel(
            name='AuthorizedVoter',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
